# Generated by Django 3.2 on 2021-06-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_recruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruit',
        ),
    ]
